// BlueprintGeneratedClass CommonMenuLibrary.CommonMenuLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UCommonMenuLibrary_C : UBlueprintFunctionLibrary {

	void ButtonScrollDown(struct UScrollBox* ScrollBox, float AmountToScroll, struct UObject* __WorldContext); // Function CommonMenuLibrary.CommonMenuLibrary_C.ButtonScrollDown // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void ButtonScrollUp(struct UScrollBox* ScrollBox, float AmountToScroll, struct UObject* __WorldContext); // Function CommonMenuLibrary.CommonMenuLibrary_C.ButtonScrollUp // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	struct UWidget* GamepadNav_HandleUniformGridNavigation(struct UUniformGridPanel* InputGrid, enum class EUINavigation Navigation, int32_t inputItemsPerRow, int32_t inputItemCount, struct UObject* __WorldContext); // Function CommonMenuLibrary.CommonMenuLibrary_C.GamepadNav_HandleUniformGridNavigation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void FocusNavTestCheck(struct UObject* __WorldContext, bool& FocusCheck); // Function CommonMenuLibrary.CommonMenuLibrary_C.FocusNavTestCheck // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void FormatPlayerDisplayName(struct FString DisplayName, int32_t maxLength, struct UObject* __WorldContext, struct FString& formatedDisplayName); // Function CommonMenuLibrary.CommonMenuLibrary_C.FormatPlayerDisplayName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	struct FText GetImageStringForCurrency(enum class ECurrencyType Type, struct UObject* __WorldContext); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetImageStringForCurrency // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void GetNPCName(enum class EMetaNPCType NPCType, struct UObject* __WorldContext, struct FText& Colors); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetNPCName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void GetRankTextFromLevel(int32_t Level, struct UObject* __WorldContext, struct FText& rankText); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetRankTextFromLevel // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void GetRecipeCategoryColor(char recipeCategory, struct UObject* __WorldContext, struct FSlateColor& Color); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetRecipeCategoryColor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void GetRecipeCategoryIcon(char recipeCategory, struct UObject* __WorldContext, struct UTexture2D*& Icon); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetRecipeCategoryIcon // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void GetNPCBlason(enum class EMetaNPCType Type, struct UObject* __WorldContext, struct UTexture2D*& blason); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetNPCBlason // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void IsShowingMenuTutorial(struct UObject* __WorldContext, bool& isShowingTutorial); // Function CommonMenuLibrary.CommonMenuLibrary_C.IsShowingMenuTutorial // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void HideMenuTutorial(struct UObject* __WorldContext); // Function CommonMenuLibrary.CommonMenuLibrary_C.HideMenuTutorial // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void GetScreenPosition(struct UWidget* Widget, struct UObject* __WorldContext, struct FVector2D& Position); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetScreenPosition // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
	void ShowMenuTutorial(struct FName TutorialId, struct FText TutorialText, struct UWidget* popUpAnchorInfo, enum class EMenuPlacement popupPlacement, struct UWidget* focusAnchorInfo, bool showBorder, struct UObject* __WorldContext, struct UMenuTutorials_C*& createdWidget); // Function CommonMenuLibrary.CommonMenuLibrary_C.ShowMenuTutorial // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void GetNPCColors(enum class EMetaNPCType NPCType, struct UObject* __WorldContext, struct FUIColors& Colors); // Function CommonMenuLibrary.CommonMenuLibrary_C.GetNPCColors // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x201e6d4
};

