// BlueprintGeneratedClass TextCanvas_FL.TextCanvas_FL_C
// Size: 0x28 (Inherited: 0x28)
struct UTextCanvas_FL_C : UBlueprintFunctionLibrary {

	void Draw Icons Material(struct UCanvas* Canvas, struct FVector2D ScreenSize, struct UMaterialInstanceDynamic* iconMaterial, struct FVector2D ScaleFactor, struct TArray<struct FIconBox>& Icon, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.Draw Icons Material // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void Add Item to Mimic(struct TArray<struct AActor*>& Array, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.Add Item to Mimic // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void SetMimicMaterial(struct UPrimitiveComponent* MeshTarget, struct UMaterialInterface* Material, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.SetMimicMaterial // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void Update Mimic(struct TArray<struct AActor*>& Array, struct UPrimitiveComponent* MeshTarget, struct UMaterialInterface* Material, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.Update Mimic // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void DrawTextBox(struct FVector2D ScaleFactor, struct FVector2D RenderTextureSize, struct UCanvas* Canvas, struct FVector2D ScreenSize, float KerningJustifyMax, float KerningJustifyMin, struct FTextBox TextBox, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.DrawTextBox // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void FindFontSize(struct TArray<struct FString>& string, struct UFont* RenderFont, struct FVector2D Scale, struct FVector2D BoxSize, float Kerning, struct UCanvas* Canvas, struct UObject* __WorldContext, float& FontScale); // Function TextCanvas_FL.TextCanvas_FL_C.FindFontSize // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void AdjustText(struct UFont* RenderFont, struct FVector2D Scale, struct FVector2D BoxSize, float Kerning, struct UCanvas* Canvas, struct FString Text, float KerningJustifyMax, float KerningJustifyMin, struct UObject* __WorldContext, float& ScaleFont, struct TArray<struct FString>& _AdjustedLines1, struct TArray<float>& _KerningScale1); // Function TextCanvas_FL.TextCanvas_FL_C.AdjustText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void DrawTextBoxArray(struct FVector2D ScaleFactor, struct FVector2D RenderTextureSize, struct FVector2D ScreenSize, struct UCanvas* Canvas, float KerningJustifyMax, float KerningJustifyMin, struct TArray<struct FTextBox>& TextBox, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.DrawTextBoxArray // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
	void Draw Icons(struct TArray<struct FIconBox>& Icons, struct UCanvas* Canvas, struct FVector2D ScreenSize, struct FVector2D UVSize, struct FVector2D ratio, struct UObject* __WorldContext); // Function TextCanvas_FL.TextCanvas_FL_C.Draw Icons // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x201e6d4
};

